# Pre-commit hooks for meeting_minutes_automator
# See https://pre-commit.com for more information

repos:
  - repo: local
    hooks:
      - id: check-python-audio-imports
        name: Check forbidden audio recording imports
        description: Enforce ADR-001 - Recording responsibility is exclusively handled by Rust
        entry: python scripts/check_forbidden_imports.py
        language: system
        files: ^python-stt/.*\.py$
        pass_filenames: true
        always_run: false

  # Future hooks (commented out for now)
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.4.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-yaml
  #     - id: check-added-large-files
  #       args: ['--maxkb=500']  # 500KB上限
