# Cargo configuration for meeting-minutes-automator
# BLOCK-005 Fix: Set APP_PYTHON to use python-stt/.venv for E2E tests
# Option C: Relative path support added to detect_python_executable()

[env]
# Python executable for E2E tests (BLOCK-005 resolution)
# Uses python-stt/.venv/bin/python with relative path support
APP_PYTHON = { value = "../python-stt/.venv/bin/python", relative = true }
