# Cargo configuration for meeting-minutes-automator
# Ensures cargo-based tests use the project-local Python virtualenv.

[env]
# Python executable for E2E tests (BLOCK-005 resolution)
# Uses python-stt/.venv/bin/python instead of system python
APP_PYTHON = { value = "python-stt/.venv/bin/python", relative = true }
