# pip-audit configuration
# SEC-001: Security vulnerability scanning

[tool.pip-audit]
# Ignore pip itself - GHSA-4xh5-x5gv-qwph will be fixed in pip 25.3
# Mitigation: Install only from trusted sources (PyPI, requirements.txt pinned versions)
# See: https://github.com/pypa/pip/pull/13550
ignore-vuln = [
    "GHSA-4xh5-x5gv-qwph"  # pip tarfile symbolic link escape (fixed in pip 25.3, planned release)
]

# Fail on vulnerabilities (except ignored)
require-hashes = false
no-deps = false
